# Generated by Django 4.1.3 on 2023-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0002_meal_uploadmeal_food_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmeal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='uploadmeal',
            name='meal',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='date_worked_out',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='uploadMeal',
        ),
    ]
