# Generated by Django 4.1.3 on 2023-04-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0007_alter_bmi_height_alter_bmi_weight_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_amount', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorieTracker.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('goal_weight', models.FloatField(null=True)),
                ('birthday', models.DateField()),
                ('num_cals', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('calories_consumed', models.FloatField(default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('goal', models.PositiveIntegerField(default=0)),
                ('all_meals', models.ManyToManyField(related_name='inventory', through='calorieTracker.PostMeal', to='calorieTracker.meal')),
                ('meal_eaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calorieTracker.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bmi',
        ),
        migrations.AddField(
            model_name='postmeal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorieTracker.profile'),
        ),
    ]
