# Generated by Django 4.1.3 on 2023-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0009_remove_exercise_name_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='activity',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
