# Generated by Django 4.1.3 on 2023-04-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0010_alter_exercise_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
    ]
