# Generated by Django 4.1.3 on 2023-04-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0011_remove_customuser_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calories_burned',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
