# Generated by Django 4.1.3 on 2023-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0013_exercise_calories_burned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight_goal',
            field=models.CharField(blank=True, choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain Weight')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='activity',
            field=models.CharField(choices=[('running', 'Running'), ('jogging', 'Jogging'), ('walking', 'Walking'), ('skipping', 'Skipping'), ('yoga', 'Yoga'), ('skiing', 'Skiing'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('dance', 'Dance'), ('squats', 'Squats'), ('pushups', 'Pushups'), ('sit ups', 'Sit ups'), ('pull ups', 'Pull ups'), ('hiking', 'Hiking'), ('lunges', 'Lunges'), ('crunches', 'Crunches'), ('pilates', 'Pilates'), ('basketball', 'Basketball'), ('circuit training', 'Circuit training'), ('tennis', 'Tennis'), ('boxing', 'Boxing')], max_length=100),
        ),
    ]
