# Generated by Django 4.2 on 2023-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0018_remove_meal_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
