# Generated by Django 4.2 on 2023-04-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0020_alter_exercise_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bmi',
        ),
    ]
