# Generated by Django 4.1.3 on 2023-03-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_discussion_options_discussion_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
