# Generated by Django 4.1.3 on 2023-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
