# Generated by Django 4.1.3 on 2023-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_community_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
