# Generated by Django 4.1.3 on 2023-03-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_community_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
