# Generated by Django 4.1.3 on 2023-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_community_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
