# Generated by Django 4.1.3 on 2023-04-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_community_discussion_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
