# Generated by Django 4.1.3 on 2023-04-19 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0012_remove_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(related_name='community_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
